services:
  server:
    build:
      context: ./serverKyswa
    container_name: kyswa-server
    env_file:
      - ./serverKyswa/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  client:
    build:
      context: ./clientKyswa
    container_name: kyswa-client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
