const ROLES = Object.freeze({
  DG: 'dg',
  ADMIN: 'administrateur',
  COMPTABLE: 'comptable',
  OUMRA: 'oumra',
  COMMERCIAL: 'commercial',
  SECRETAIRE: 'secretaire',
  BILLETS: 'billets',
  ZIARA: 'ziara',
  SOCIAL: 'social',
});

const PERMISSIONS = Object.freeze({
  STATS_READ: 'stats:read',
  CLIENTS_READ: 'clients:read',
  CLIENTS_CREATE: 'clients:create',
  CLIENTS_UPDATE: 'clients:update',
  CLIENTS_DELETE: 'clients:delete',
  CLIENTS_SCAN_DOCUMENT: 'clients:scan-document',
  CLIENTS_UPLOAD_PHOTO: 'clients:upload-photo',
  MESSAGES_AUDIT_READ: 'messages:audit:read',
  PACKAGES_READ: 'packages:read',
  PACKAGES_MANAGE: 'packages:manage',
  SHOP_READ: 'shop:read',
  SHOP_CREATE: 'shop:create',
  SHOP_UPDATE: 'shop:update',
  SHOP_DELETE: 'shop:delete',
  SHOP_MANAGE_STOCK: 'shop:manage-stock',
  COMPTABILITE_READ: 'comptabilite:read',
  COMPTABILITE_CREATE: 'comptabilite:create',
  COMPTABILITE_UPDATE: 'comptabilite:update',
  COMPTABILITE_DELETE: 'comptabilite:delete',
  PAIEMENTS_READ: 'paiements:read',
  PAIEMENTS_CREATE: 'paiements:create',
  PAIEMENTS_UPDATE: 'paiements:update',
  PAIEMENTS_DELETE: 'paiements:delete',
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.DG]: new Set([
    PERMISSIONS.STATS_READ,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_DELETE,
    PERMISSIONS.CLIENTS_SCAN_DOCUMENT,
    PERMISSIONS.CLIENTS_UPLOAD_PHOTO,
    PERMISSIONS.MESSAGES_AUDIT_READ,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.PACKAGES_MANAGE,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_DELETE,
    PERMISSIONS.SHOP_MANAGE_STOCK, // DG: Accès complet au shop
    PERMISSIONS.COMPTABILITE_READ,
    PERMISSIONS.COMPTABILITE_CREATE,
    PERMISSIONS.COMPTABILITE_UPDATE,
    PERMISSIONS.COMPTABILITE_DELETE,
    PERMISSIONS.PAIEMENTS_READ,
    PERMISSIONS.PAIEMENTS_CREATE,
    PERMISSIONS.PAIEMENTS_UPDATE,
    PERMISSIONS.PAIEMENTS_DELETE,
  ]),
  [ROLES.ADMIN]: new Set([
    PERMISSIONS.STATS_READ,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_DELETE,
    PERMISSIONS.CLIENTS_SCAN_DOCUMENT,
    PERMISSIONS.CLIENTS_UPLOAD_PHOTO,
    PERMISSIONS.MESSAGES_AUDIT_READ,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.PACKAGES_MANAGE,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_DELETE,
    PERMISSIONS.SHOP_MANAGE_STOCK, // Administrateur: Accès complet au shop
    // Pas d'accès direct aux paiements et comptabilité pour l'admin
  ]),
  [ROLES.COMPTABLE]: new Set([
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_MANAGE_STOCK, // Comptable: Accès shop sans suppression de produit
    PERMISSIONS.COMPTABILITE_READ,
    PERMISSIONS.COMPTABILITE_CREATE,
    PERMISSIONS.COMPTABILITE_UPDATE,
    PERMISSIONS.COMPTABILITE_DELETE,
    PERMISSIONS.PAIEMENTS_READ,
    PERMISSIONS.PAIEMENTS_CREATE,
    PERMISSIONS.PAIEMENTS_UPDATE,
    PERMISSIONS.PAIEMENTS_DELETE,
  ]),
  [ROLES.COMMERCIAL]: new Set([
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_SCAN_DOCUMENT,
    PERMISSIONS.CLIENTS_UPLOAD_PHOTO,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_DELETE,
    PERMISSIONS.SHOP_MANAGE_STOCK, // Commercial: Accès complet au shop
    // Pas d'accès aux paiements et comptabilité
  ]),
  [ROLES.OUMRA]: new Set([
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_SCAN_DOCUMENT,
    PERMISSIONS.CLIENTS_UPLOAD_PHOTO,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_DELETE,
    PERMISSIONS.SHOP_MANAGE_STOCK, // Responsable Oumra: Accès complet au shop
    // Pas d'accès aux paiements et comptabilité
  ]),
  [ROLES.BILLETS]: new Set([
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_SCAN_DOCUMENT,
    PERMISSIONS.CLIENTS_UPLOAD_PHOTO,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_DELETE,
    PERMISSIONS.SHOP_MANAGE_STOCK, // Responsable Billets: Accès complet au shop
    // Pas d'accès aux paiements et comptabilité
  ]),
  [ROLES.SECRETAIRE]: new Set([
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_SCAN_DOCUMENT,
    PERMISSIONS.CLIENTS_UPLOAD_PHOTO,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.SHOP_READ,
    // Pas d'accès aux paiements et comptabilité
  ]),
  [ROLES.ZIARA]: new Set([
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_SCAN_DOCUMENT,
    PERMISSIONS.CLIENTS_UPLOAD_PHOTO,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_CREATE,
    PERMISSIONS.SHOP_UPDATE,
    PERMISSIONS.SHOP_DELETE,
    PERMISSIONS.SHOP_MANAGE_STOCK, // Responsable Ziarra: Accès complet au shop
    // Pas d'accès aux paiements et comptabilité
  ]),
  [ROLES.SOCIAL]: new Set([
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.PACKAGES_READ,
    PERMISSIONS.SHOP_READ, // Social: Lecture seule pour le shop
    // Pas d'accès aux paiements et comptabilité
  ]),
});

const normalizeRole = (role) => (typeof role === 'string' ? role.toLowerCase() : '');

const hasPermission = (role, permission) => {
  const normalizedRole = normalizeRole(role);
  const granted = ROLE_PERMISSIONS[normalizedRole];
  return Boolean(granted && granted.has(permission));
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  normalizeRole,
  hasPermission,
};
